### ISSUE TITLE
App crashes on iOS 14

### ISSUE THREAD

**Issue by NetAnarchy** [sourcelocation/Evyrest#2]
Hi.

I’ve tried to touch this app, but in my environment iOS 14.7.1 (iPhone XS), app crashes when I open.
Perhaps it could be my environment’s fault, however I also tried another app [WallpaperSetter](https://github.com/Skittyblock/WallpaperSetter) that didn’t respond either, so I suspect tweaks related wallpaper-customization will be crashed on iOS 14.x environment.

…Yes I know people are using TrollStore on iOS 15 higher, but could you help us solve this issue?

Thank you very much😊

**Comment by EncryptionEnjoyer** [comment]
Same for me, just iPadOS 14.6, iPad 8th gen

**Comment by sourcelocation** [comment]
iOS 14 is not supported, sorry. >15

**Comment by NetAnarchy** [comment]
Thanks!
